"""Session-mutation operations for slash commands (/retry, /undo) and
read-only aggregators (/status, /usage). Operates on the webui's own
JSON Session store (api/models.py), not on hermes-agent's SQLite.

Behavior parity reference: gateway/run.py:_handle_*_command in
the hermes-agent repo.
"""
from __future__ import annotations
import copy
import logging
import re
from typing import Any

from api.config import LOCK, SESSIONS_MAX, _get_session_agent_lock
from api.models import get_session, SESSIONS, Session
from api.session_events import publish_session_list_changed

logger = logging.getLogger(__name__)

AUTO_TITLE_LABELS = {'untitled', 'new chat'}


def session_has_manual_title(session) -> bool:
    """Return whether adaptive title refresh should leave this title alone."""
    return getattr(session, 'manual_title', False) is True


def apply_session_title_rename(session, raw_title) -> str:
    """Apply user-driven rename semantics to a Session object.

    Non-empty custom titles are protected from adaptive refresh. Clearing the
    title, or resetting it to an automatic label, removes that protection so the
    normal auto-title path can run again.
    """
    title = str(raw_title or '').strip()[:80]
    if not title:
        title = 'Untitled'
    manual_title = title.strip().casefold() not in AUTO_TITLE_LABELS
    session.title = title
    session.manual_title = manual_title
    session.llm_title_generated = False
    return title


def mark_session_title_generated(session) -> None:
    """Mark a session title as generated by the title model."""
    session.llm_title_generated = True
    session.manual_title = False


def _truncate_at_last_user(messages):
    history = messages or []
    last_user_idx = None
    for i in range(len(history) - 1, -1, -1):
        if isinstance(history[i], dict) and history[i].get('role') == 'user':
            last_user_idx = i
            break
    if last_user_idx is None:
        return None
    return history[:last_user_idx]


def _truncation_watermark_for(messages):
    history = list(messages or [])
    if not history:
        return 0.0
    try:
        return float(history[-1].get('timestamp') or 0)
    except (AttributeError, TypeError, ValueError):
        return 0.0


_RETRY_SAFE_ERROR_RE = re.compile(
    r'^\*\*Error:\*\*\s+(Provider\s+.+|No response received after context compression\.\s*Please retry\.)',
    re.IGNORECASE,
)

_RECOVERED_SIGNALS = (
    'recovered',
    'partial output',
    'run journal',
    'could not continue',
)


def _is_retry_safe_error_marker(message: dict) -> bool:
    """Return True for a strict, empty-failed-turn assistant error marker.

    A retry-safe tail row is assistant-only, carries plain text, has no
    tool_calls/tool_use, and matches a narrow set of explicit retry markers.

    An interrupted marker (``type=interrupted``) is only safe when it carries
    no recovered output. If the marker content mentions recovered partial
    output, the tail has meaningful output and must branch.
    """
    if not isinstance(message, dict):
        return False
    if message.get('role') != 'assistant':
        return False
    # No tool calls or tool_use content
    if message.get('tool_calls'):
        return False
    content = message.get('content', '')
    if isinstance(content, list):
        has_tool_use = any(
            isinstance(p, dict) and p.get('type') in ('tool_use', 'tool_result')
            for p in content
        )
        if has_tool_use:
            return False
        text_parts = [
            str(p.get('text', '') if isinstance(p, dict) else p)
            for p in content
        ]
        text = ''.join(text_parts)
    elif isinstance(content, str):
        text = content
    else:
        text = str(content)

    is_interrupted_marker = message.get('type') == 'interrupted' and message.get('_error')
    if is_interrupted_marker:
        # An interrupted marker is only retry-safe when it does NOT carry
        # recovered partial output. If the content mentions recovered output
        # or contains substantial prose, treat it as meaningful and branch.
        stripped = text.strip()
        if not stripped:
            return True
        if len(stripped) > 100:
            return False
        if any(sig in stripped.lower() for sig in _RECOVERED_SIGNALS):
            return False
        return True

    if not _RETRY_SAFE_ERROR_RE.match(text.strip()):
        return False
    return True


def _retry_tail_has_meaningful_output(tail: list) -> bool:
    """Return True if the post-user tail contains recoverable output.

    Any tool role, assistant tool_calls, normal assistant prose, artifacts,
    media, or mixed rows make the tail meaningful and force a branch retry.
    """
    if not isinstance(tail, list) or not tail:
        return False
    # A single safe error marker is NOT meaningful
    if len(tail) == 1 and _is_retry_safe_error_marker(tail[0]):
        return False
    return True


def retry_last(session_id: str) -> dict[str, Any]:
    """Retry the interrupted/pending turn without destructive rewind.

    Pending sidecar text wins over stale persisted history. Otherwise a
    meaningful post-user tail branches; strict no-output failures retry in
    place. Raises KeyError for missing sessions and ValueError when no user
    turn exists.
    """
    # Acquire the per-session agent lock as the outermost lock so that the
    # read-modify-write of s.messages is serialised with the periodic
    # checkpoint thread, cancel_stream, and all other session writers.
    # Lock ordering: _agent_lock → LOCK for in-memory mutation, then release
    # LOCK before save() acquires the separate session-index write lock.
    with _get_session_agent_lock(session_id):
        # get_session() acquires the module-level LOCK internally, and LOCK is
        # a non-reentrant threading.Lock — so it must be called outside our own
        # `with LOCK:` block to avoid self-deadlocking. Session.save() is also
        # called after releasing LOCK; it acquires the separate index write lock.
        #
        # The race we close is the read-modify-write of s.messages: two
        # concurrent /api/session/retry calls could otherwise both compute the
        # same last_user_idx from the same history and double-truncate. We
        # serialize just the in-memory mutation; persistence happens inside
        # the per-session lock so the checkpoint thread cannot race us.
        #
        # Stale-object guard: on a cache miss, two concurrent get_session()
        # calls can each load and cache a *different* Session instance for the
        # same session_id (the second store clobbers the first). Re-bind to
        # the canonical cached instance inside the lock so the mutation lands
        # on the object the next reader will see, not a stale parallel copy.
        s = get_session(session_id)  # raises KeyError if missing
        branch = None
        branch_response = None
        pending_response = None
        with LOCK:
            s = SESSIONS.get(session_id, s)

            # Prefer the explicit interrupted/pending turn state over scanning
            # backward in the persisted transcript. This prevents retry from
            # jumping to an older user turn when the live sidecar already knows
            # the interrupted text (#retry-target-anchoring).
            pending_text = getattr(s, 'pending_user_message', None)
            if pending_text:
                # Guard against the narrow race where the pending turn was
                # already materialized into messages (e.g. by a streaming error
                # recovery path) while pending_user_message is still set. In
                # that case, fall through to the persisted-tail logic so the
                # materialized user + interrupted marker are handled correctly
                # instead of duplicating the turn on resend.
                history = s.messages or []
                last_user_idx = None
                for i in range(len(history) - 1, -1, -1):
                    if history[i].get('role') == 'user':
                        last_user_idx = i
                        break
                if last_user_idx is not None:
                    last_persisted_text = _extract_text(history[last_user_idx].get('content', ''))
                else:
                    last_persisted_text = ''
                if last_persisted_text and _extract_text(pending_text) == last_persisted_text:
                    # Pending already materialized — fall through to persisted logic.
                    pending_text = None
                    s.active_stream_id = None
                    s.pending_user_message = None
                    s.pending_attachments = []
                    s.pending_started_at = None

            if pending_text:
                s.active_stream_id = None
                s.pending_user_message = None
                s.pending_attachments = []
                s.pending_started_at = None
                pending_response = {
                    'mode': 'pending',
                    'last_user_text': _extract_text(pending_text),
                    'removed_count': 0,
                }
            else:
                history = s.messages or []
                last_user_idx = None
                for i in range(len(history) - 1, -1, -1):
                    if history[i].get('role') == 'user':
                        last_user_idx = i
                        break
                if last_user_idx is None:
                    raise ValueError('No previous message to retry.')

                last_user_text = _extract_text(history[last_user_idx].get('content', ''))
                removed_count = len(history) - last_user_idx
                tail = history[last_user_idx + 1:]

                # If the interrupted turn produced visible output, branch instead of
                # rewriting the active transcript in place (#2361).
                if _retry_tail_has_meaningful_output(tail):
                    prefix_messages = history[:last_user_idx]
                    context_prefix = []
                    if isinstance(getattr(s, 'context_messages', None), list) and s.context_messages:
                        truncated_context = _truncate_at_last_user(s.context_messages)
                        if truncated_context is not None:
                            context_prefix = truncated_context
                    source_title = s.title or 'Untitled'
                    branch_title = f"{source_title} (retry)"
                    branch = Session(
                        workspace=s.workspace,
                        model=s.model,
                        model_provider=getattr(s, 'model_provider', None),
                        profile=getattr(s, 'profile', None),
                        title=branch_title,
                        messages=copy.deepcopy(prefix_messages),
                        project_id=getattr(s, 'project_id', None),
                        personality=getattr(s, 'personality', None),
                        enabled_toolsets=getattr(s, 'enabled_toolsets', None),
                        context_length=getattr(s, 'context_length', None),
                        threshold_tokens=getattr(s, 'threshold_tokens', None),
                        context_messages=copy.deepcopy(context_prefix),
                        gateway_routing=copy.deepcopy(getattr(s, 'gateway_routing', None)),
                        context_engine=getattr(s, 'context_engine', None),
                        context_engine_state=copy.deepcopy(getattr(s, 'context_engine_state', None) or {}),
                        parent_session_id=session_id,
                        session_source='fork',
                    )
                    SESSIONS[branch.session_id] = branch
                    if hasattr(SESSIONS, 'move_to_end'):
                        SESSIONS.move_to_end(branch.session_id)
                    while len(SESSIONS) > SESSIONS_MAX:
                        try:
                            SESSIONS.popitem(last=False)
                        except TypeError:
                            SESSIONS.popitem()
                    branch_response = {
                        'mode': 'branch',
                        'session_id': branch.session_id,
                        'parent_session_id': session_id,
                        'last_user_text': last_user_text,
                        'removed_count': removed_count,
                    }
                else:
                    s.messages = history[:last_user_idx]
                    s.truncation_watermark = _truncation_watermark_for(s.messages)
                    if isinstance(getattr(s, 'context_messages', None), list) and s.context_messages:
                        truncated_context = _truncate_at_last_user(s.context_messages)
                        if truncated_context is not None:
                            s.context_messages = truncated_context

            # Keep all mutations inside the per-session agent lock so the
            # checkpoint thread cannot race us. Save below happens after
            # releasing module LOCK but before releasing the per-session lock.
        if pending_response is not None:
            s.save()
            return pending_response

        if branch_response is not None:
            if branch is None:
                raise RuntimeError('Retry branch creation failed.')
            branch.save()
            publish_session_list_changed(
                'session_branch',
                profile=getattr(branch, 'profile', None),
                session_id=getattr(branch, 'session_id', None),
            )
            return branch_response

        s.save()
    return {
        'mode': 'in_place',
        'last_user_text': last_user_text,
        'removed_count': removed_count,
    }


def undo_last(session_id: str) -> dict[str, Any]:
    """Remove the most recent user message and everything after it.

    Mirrors gateway/run.py:_handle_undo_command. Returns a preview of the
    removed text so the UI can confirm to the user.

    Raises:
        KeyError: session not found
        ValueError: no user message in transcript
    """
    # Acquire the per-session agent lock as the outermost lock so that the
    # read-modify-write of s.messages is serialised with the periodic
    # checkpoint thread, cancel_stream, and all other session writers.
    # Lock ordering: _agent_lock → LOCK for in-memory mutation, then release
    # LOCK before save() acquires the separate session-index write lock.
    with _get_session_agent_lock(session_id):
        s = get_session(session_id)  # acquires LOCK transiently
        with LOCK:
            # Stale-object guard — see retry_last for the rationale.
            s = SESSIONS.get(session_id, s)
            history = s.messages or []
            last_user_idx = None
            for i in range(len(history) - 1, -1, -1):
                if history[i].get('role') == 'user':
                    last_user_idx = i
                    break
            if last_user_idx is None:
                raise ValueError('Nothing to undo.')

            removed_text = _extract_text(history[last_user_idx].get('content', ''))
            removed_count = len(history) - last_user_idx
            s.messages = history[:last_user_idx]
            s.truncation_watermark = _truncation_watermark_for(s.messages)
            if isinstance(getattr(s, 'context_messages', None), list) and s.context_messages:
                truncated_context = _truncate_at_last_user(s.context_messages)
                if truncated_context is not None:
                    s.context_messages = truncated_context
        s.save()  # outside LOCK -- save() re-acquires LOCK via _write_session_index()
    preview = (removed_text[:40] + '...') if len(removed_text) > 40 else removed_text
    return {
        'removed_count': removed_count,
        'removed_preview': preview,
    }


def session_status(session_id: str) -> dict[str, Any]:
    """Return a snapshot of session state for /status.

    Webui equivalent of gateway/run.py:_handle_status_command. The agent's
    "agent_running" comes from `session_key in self._running_agents`; the
    webui equivalent is whether the session has an active stream
    (active_stream_id is set).
    """
    s = get_session(session_id)
    inp = int(s.input_tokens or 0)
    out = int(s.output_tokens or 0)
    profile = getattr(s, 'profile', None) or 'default'
    try:
        from api.profiles import get_hermes_home_for_profile
        hermes_home = str(get_hermes_home_for_profile(profile))
    except Exception:
        hermes_home = ''
    return {
        'session_id': s.session_id,
        'title': s.title,
        'model': s.model,
        'profile': profile,
        'hermes_home': hermes_home,
        'workspace': s.workspace,
        'personality': s.personality,
        'message_count': len(s.messages or []),
        'created_at': s.created_at,
        'updated_at': s.updated_at,
        'agent_running': bool(getattr(s, 'active_stream_id', None)),
        'input_tokens': inp,
        'output_tokens': out,
        'total_tokens': inp + out,
        'estimated_cost': s.estimated_cost,
    }


def session_usage(session_id: str) -> dict[str, Any]:
    """Return token usage and cost for /usage.

    Mirrors gateway/run.py:_handle_usage_command's basic counters. The
    agent shows additional fields (rate-limit headroom etc.) that depend
    on provider API responses we don't have in webui -- those are deferred.
    """
    s = get_session(session_id)
    inp = int(s.input_tokens or 0)
    out = int(s.output_tokens or 0)
    return {
        'input_tokens': inp,
        'output_tokens': out,
        'total_tokens': inp + out,
        'estimated_cost': s.estimated_cost,
        'model': s.model,
    }


def _extract_text(content: Any) -> str:
    """Flatten message content to plain text. Agent stores either a string
    or a list of {type, text|...} parts; webui needs the user-typed text."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for p in content:
            if isinstance(p, dict) and p.get('type') == 'text':
                parts.append(p.get('text', ''))
        return ' '.join(parts)
    return str(content)
