"""Postgres-backed WebUI session store.

Implements the canonical ``api.session_store.SessionStore`` contract against
PostgreSQL, proving the abstraction is not coupled to the embedded SQLite
backend (or the filesystem): same sessions/messages/tool_calls/
context_messages/anchor_scenes model, ``extra_json`` as JSONB, a meta table
for the revision counter and cutover markers, and the same stale-writer
fenced upsert.

Not wired into production config files — selected at runtime by
``api.models.get_session_store()`` when ``HERMES_SESSION_STORE_PG_DSN`` is
set (fail-closed on an inactive store), and exercised by the backend
contract tests (tests/test_session_store_contract.py).
"""
from __future__ import annotations

import json
import threading
import time
from typing import Any, Sequence

from api.webui_session_sqlite import (
    _ALWAYS_PRESENT_FIELDS,  # noqa: F401  (contract parity reference)
    _SESSION_BOOL_FIELDS,
    _SESSION_JSON_FIELDS,
    _SESSION_SCALAR_FIELDS,
    DeletedSessionWriteError,
    RetiredSessionWriteError,
    StaleSessionWriteError,
    _is_safe_session_id,
    _json_dump,
)

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS sessions (
    session_id TEXT PRIMARY KEY,
    title TEXT,
    workspace TEXT,
    model TEXT,
    model_provider TEXT,
    model_explicit_pick_signature TEXT,
    created_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION,
    pinned INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0,
    project_id TEXT,
    profile TEXT,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    estimated_cost DOUBLE PRECISION DEFAULT 0,
    cache_read_tokens INTEGER DEFAULT 0,
    cache_write_tokens INTEGER DEFAULT 0,
    personality TEXT,
    active_stream_id TEXT,
    pending_user_message TEXT,
    pending_started_at DOUBLE PRECISION,
    pending_user_source TEXT,
    pending_attachments TEXT,
    compression_anchor_visible_idx INTEGER,
    compression_anchor_message_key TEXT,
    compression_anchor_summary TEXT,
    pre_compression_snapshot INTEGER DEFAULT 0,
    context_engine TEXT,
    compression_anchor_engine TEXT,
    compression_anchor_mode TEXT,
    compression_anchor_details TEXT,
    context_engine_state TEXT,
    context_length INTEGER,
    threshold_tokens INTEGER,
    last_prompt_tokens INTEGER,
    post_compression_context_tokens_estimate INTEGER,
    compression_recovery TEXT,
    recommended_recovery_action TEXT,
    compression_recovery_source_session_id TEXT,
    compression_recovery_action TEXT,
    truncation_watermark DOUBLE PRECISION,
    truncation_boundary DOUBLE PRECISION,
    gateway_routing TEXT,
    gateway_routing_history TEXT,
    llm_title_generated INTEGER DEFAULT 0,
    manual_title INTEGER DEFAULT 0,
    clear_generation TEXT,
    parent_session_id TEXT,
    worktree_path TEXT,
    worktree_branch TEXT,
    worktree_repo_root TEXT,
    worktree_created_at DOUBLE PRECISION,
    is_cli_session INTEGER DEFAULT 0,
    source_tag TEXT,
    raw_source TEXT,
    session_source TEXT,
    source_label TEXT,
    read_only INTEGER DEFAULT 0,
    enabled_toolsets TEXT,
    composer_draft TEXT,
    process_wakeup_pause TEXT,
    share_token TEXT,
    share_created_at DOUBLE PRECISION,
    message_count INTEGER DEFAULT 0,
    anchor_scene_index TEXT,
    anchor_scene_index_hash TEXT,
    anchor_activity_scenes_json TEXT,
    created_workspace TEXT,
    intentional_shrink_generation TEXT,
    user_id TEXT,
    chat_id TEXT,
    session_key TEXT,
    platform TEXT,
    extra_json TEXT,
    generation INTEGER NOT NULL DEFAULT 0,
    null_fields_json TEXT
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    idx INTEGER NOT NULL,
    message_json TEXT NOT NULL,
    UNIQUE(session_id, idx)
);
CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id, idx);

CREATE TABLE IF NOT EXISTS tool_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    idx INTEGER NOT NULL,
    tool_call_json TEXT NOT NULL,
    UNIQUE(session_id, idx)
);
CREATE INDEX IF NOT EXISTS idx_tool_calls_session ON tool_calls(session_id, idx);

CREATE TABLE IF NOT EXISTS context_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    idx INTEGER NOT NULL,
    message_json TEXT NOT NULL,
    UNIQUE(session_id, idx)
);
CREATE INDEX IF NOT EXISTS idx_context_messages_session ON context_messages(session_id, idx);

CREATE TABLE IF NOT EXISTS anchor_scenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_hash TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    scene_json TEXT NOT NULL,
    UNIQUE(scene_hash, session_id)
);

CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Per-SID incarnation authority. Deliberately NON-cascading (no FK, no
-- ON DELETE CASCADE): survives delete_session() so a stale pre-delete
-- writer cannot resurrect the transcript at generation 1.
CREATE TABLE IF NOT EXISTS session_incarnations (
    session_id TEXT PRIMARY KEY,
    incarnation INTEGER NOT NULL,
    retired INTEGER NOT NULL DEFAULT 0,
    retired_generation INTEGER NOT NULL DEFAULT 0
);

-- Placeholder for the cleanup-lease protocol (behavior lands separately).
CREATE TABLE IF NOT EXISTS cleanup_leases (
    session_id TEXT PRIMARY KEY,
    owner TEXT NOT NULL,
    error TEXT,
    updated_at DOUBLE PRECISION NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 1
);

-- Durable residual-cleanup phases. Separate from cleanup_leases: leases mean
-- "the authoritative store delete FAILED" (cleared on lifecycle_delete
-- success). Phase rows mean "the delete SUCCEEDED, these residual artifacts
-- remain" — recorded in the same transaction as the delete, cleared per
-- phase as the executor drains them. attempts counts failed executor runs
-- (recorded at delete time with attempts=0).
CREATE TABLE IF NOT EXISTS cleanup_phases (
    session_id TEXT NOT NULL,
    phase TEXT NOT NULL,
    owner TEXT NOT NULL,
    error TEXT,
    updated_at DOUBLE PRECISION NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (session_id, phase)
);
"""


class WebUIPostgresSessionDB:
    """SessionStore implementation backed by PostgreSQL."""

    backend = "postgres"
    supports_generation = True
    supports_revision_counter = True
    persists_without_sidecar = True

    def __init__(self, dsn: str, *, created_by: str = "app"):
        import psycopg

        self._dsn = dsn
        self._created_by = created_by
        self._psycopg = psycopg
        self._local = threading.local()
        # Per-store failure state, mirrors the SQLite store: mark entries are
        # dicts (see api.models Session.load).
        self.unreadable_sids: dict[str, dict] = {}
        self._ensure_schema()

    def _conn(self):
        conn = getattr(self._local, "conn", None)
        if conn is None or conn.closed:
            conn = self._psycopg.connect(self._dsn, autocommit=False)
            self._local.conn = conn
        return conn

    def _ensure_schema(self) -> None:
        conn = self._conn()
        with conn:
            for stmt in _SCHEMA_SQL.split(";"):
                stmt = stmt.strip()
                if stmt:
                    conn.execute(stmt)
            # v4 columns for databases created by earlier versions.
            conn.execute(
                "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS generation INTEGER NOT NULL DEFAULT 0"
            )
            conn.execute(
                "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS null_fields_json TEXT"
            )
            # Backfill the incarnation authority for pre-existing rows.
            conn.execute(
                "INSERT INTO session_incarnations "
                "(session_id, incarnation, retired, retired_generation) "
                "SELECT session_id, 1, 0, 0 FROM sessions "
                "ON CONFLICT (session_id) DO NOTHING"
            )
            if conn.execute("SELECT 1 FROM meta WHERE key = 'created_by'").fetchone() is None:
                has_rows = conn.execute("SELECT 1 FROM sessions LIMIT 1").fetchone() is not None
                if self._created_by == "migration":
                    # Staged from creation: a database the migration script
                    # opens is incomplete until the script publishes it, even
                    # if this process dies before writing a single row.
                    conn.execute(
                        "INSERT INTO meta (key, value) VALUES ('created_by', 'migration')"
                    )
                    conn.execute(
                        "INSERT INTO meta (key, value) VALUES ('migration_complete', '0')"
                    )
                else:
                    conn.execute(
                        "INSERT INTO meta (key, value) VALUES ('created_by', %s)",
                        ("legacy" if has_rows else "app",),
                    )

    def close(self) -> None:
        conn = getattr(self._local, "conn", None)
        if conn is not None and not conn.closed:
            conn.close()
        self._local.conn = None

    # -- meta / revision / cutover ----------------------------------------

    def _bump_revision(self, conn) -> None:
        conn.execute(
            "INSERT INTO meta (key, value) VALUES ('revision', '1') "
            "ON CONFLICT(key) DO UPDATE SET value = CAST(CAST(meta.value AS INTEGER) + 1 AS TEXT)"
        )

    def get_revision(self) -> int:
        try:
            row = self._conn().execute(
                "SELECT value FROM meta WHERE key = 'revision'"
            ).fetchone()
            return int(row[0]) if row is not None else 0
        except Exception:
            return int(time.time_ns())

    def set_meta(self, key: str, value: str) -> None:
        conn = self._conn()
        with conn:
            conn.execute(
                "INSERT INTO meta (key, value) VALUES (%s, %s) "
                "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                (key, value),
            )

    def get_meta(self, key: str) -> str | None:
        try:
            row = self._conn().execute(
                "SELECT value FROM meta WHERE key = %s", (key,)
            ).fetchone()
            return row[0] if row is not None else None
        except Exception:
            return None

    def is_active(self) -> bool:
        """Durable cutover check, fail-closed (mirrors the SQLite store).

        Authority requires readable, recognizable markers: an app-created or
        legacy (pre-marker) database is active; a migration database is only
        active once migration_complete=1. Unreadable, missing, or unknown
        markers deny authority — a configured Postgres store must never fail
        open.
        """
        try:
            rows = self._conn().execute("SELECT key, value FROM meta").fetchall()
            meta = {row[0]: row[1] for row in rows}
        except Exception:
            return False
        created_by = meta.get("created_by")
        if created_by == "migration":
            return meta.get("migration_complete") == "1"
        if created_by in ("app", "legacy"):
            return True
        return False

    # -- reads -------------------------------------------------------------

    def list_sessions(self) -> list[dict[str, Any]]:
        cur = self._conn().execute(
            "SELECT * FROM sessions ORDER BY pinned DESC, updated_at DESC, created_at DESC"
        )
        cols = [c.name for c in cur.description]
        return [self._row_to_metadata(dict(zip(cols, row))) for row in cur.fetchall()]

    def session_exists(self, sid: str) -> bool:
        if not _is_safe_session_id(sid):
            return False
        row = self._conn().execute(
            "SELECT 1 FROM sessions WHERE session_id = %s", (sid,)
        ).fetchone()
        return row is not None

    def _fetch_row(self, sid: str) -> dict[str, Any] | None:
        # One PK-indexed LEFT JOIN against the incarnation authority so the
        # loaded content and its (generation, incarnation) writer token are a
        # single atomic read. LEFT (not INNER): a missing authority row must
        # never hide a session from reads — it yields incarnation=None and
        # every write path then fails closed.
        cur = self._conn().execute(
            "SELECT s.*, i.incarnation AS incarnation "
            "FROM sessions s "
            "LEFT JOIN session_incarnations i ON i.session_id = s.session_id "
            "WHERE s.session_id = %s",
            (sid,),
        )
        row = cur.fetchone()
        if row is None:
            return None
        cols = [c.name for c in cur.description]
        return dict(zip(cols, row))

    def read_session(self, sid: str) -> dict[str, Any] | None:
        if not _is_safe_session_id(sid):
            return None
        d = self._fetch_row(sid)
        if d is None:
            return None
        session = self._row_to_session(d)
        session["messages"] = self._read_json_table("messages", "message_json", sid)
        session["tool_calls"] = self._read_json_table("tool_calls", "tool_call_json", sid)
        session["context_messages"] = self._read_json_table("context_messages", "message_json", sid)
        return session

    def read_metadata_only(self, sid: str) -> dict[str, Any] | None:
        if not _is_safe_session_id(sid):
            return None
        d = self._fetch_row(sid)
        if d is None:
            return None
        return self._row_to_metadata(d, include_computed=False)

    def _read_json_table(self, table: str, column: str, sid: str) -> list[dict[str, Any]]:
        cur = self._conn().execute(
            f"SELECT {column} FROM {table} WHERE session_id = %s ORDER BY idx", (sid,)
        )
        return [json.loads(row[0]) for row in cur.fetchall()]

    # -- writes ------------------------------------------------------------

    def write_session(
        self,
        session: dict[str, Any],
        *,
        expected_generation: int | None = None,
        expected_incarnation: int | None = None,
        force: bool = False,
        fresh_incarnation: bool = False,
    ) -> dict[str, Any]:
        if not isinstance(session, dict):
            raise TypeError("session must be a dict")
        sid = session.get("session_id")
        if not _is_safe_session_id(sid):
            raise ValueError(f"Unsafe session_id {sid!r}")

        import copy

        payload = copy.deepcopy(session)
        messages = payload.pop("messages", [])
        tool_calls = payload.pop("tool_calls", [])
        context_messages = payload.pop("context_messages", [])
        if "message_count" not in payload:
            payload["message_count"] = len(messages)

        conn = self._conn()
        with conn:
            self._bump_revision(conn)
            self._write_session_row(
                conn, sid, payload,
                expected_generation=expected_generation,
                expected_incarnation=expected_incarnation,
                force=force,
                fresh_incarnation=fresh_incarnation,
            )
            self._write_json_table(conn, "messages", "message_json", sid, messages)
            self._write_json_table(conn, "tool_calls", "tool_call_json", sid, tool_calls)
            self._write_json_table(conn, "context_messages", "message_json", sid, context_messages)
            self._write_anchor_scenes(conn, sid, payload.get("anchor_activity_scenes", {}))
        return self.read_session(sid) or {}

    def _write_session_row(
        self,
        conn,
        sid: str,
        payload: dict[str, Any],
        *,
        expected_generation: int | None = None,
        expected_incarnation: int | None = None,
        force: bool = False,
        fresh_incarnation: bool = False,
    ) -> None:
        cols = ["session_id"]
        vals: list[Any] = [sid]
        for field in _SESSION_SCALAR_FIELDS:
            if field == "anchor_scene_index_hash":
                continue
            cols.append(field)
            v = payload.get(field)
            if v is None and field in _SESSION_BOOL_FIELDS:
                vals.append(0)
            elif v is None:
                vals.append(None)
            elif field in _SESSION_JSON_FIELDS:
                vals.append(_json_dump(v))
            elif field in _SESSION_BOOL_FIELDS:
                vals.append(1 if v else 0)
            else:
                vals.append(v)
        cols.append("anchor_scene_index_hash")
        idx = payload.get("anchor_scene_index")
        vals.append(_json_dump(idx) if isinstance(idx, dict) else None)
        cols.append("anchor_activity_scenes_json")
        scenes = payload.get("anchor_activity_scenes")
        vals.append(_json_dump(scenes) if scenes is not None else None)
        consumed = set(_SESSION_SCALAR_FIELDS) | {
            "session_id", "anchor_activity_scenes",
            # Store-owned fence values ride the authority/column, never the
            # forward-compat bag.
            "generation", "incarnation",
        }
        extra = {k: v for k, v in payload.items() if k not in consumed}
        cols.append("extra_json")
        vals.append(_json_dump(extra) if extra else None)
        # Key-presence contract: explicitly-None keys read back as present None.
        null_fields = sorted(k for k, v in payload.items() if v is None)
        cols.append("null_fields_json")
        vals.append(_json_dump(null_fields) if null_fields else None)

        # Same decision table as the SQLite store: the writer token is the
        # (incarnation, generation) pair — live rows CAS on both against the
        # JOINed authority; absent rows consult the incarnation authority.
        # force may overwrite a LIVE row only — it never inserts an absent
        # one; fresh_incarnation is the only lease onto a retired SID.
        # expected_incarnation is ignored on the absent-row branch (the
        # generation lineage + retired authority already discriminate).
        row = conn.execute(
            "SELECT s.generation AS generation, i.incarnation AS incarnation, "
            "i.retired AS retired "
            "FROM sessions s "
            "LEFT JOIN session_incarnations i ON i.session_id = s.session_id "
            "WHERE s.session_id = %s",
            (sid,),
        ).fetchone()
        current_generation = int(row[0] or 0) if row is not None else None
        cas_guard = False
        if current_generation is not None:
            if force:
                new_generation = current_generation + 1
            elif expected_generation is None or int(expected_generation) != current_generation:
                raise StaleSessionWriteError(
                    f"Refusing to overwrite session {sid!r}: expected generation "
                    f"{expected_generation!r} != persisted {current_generation!r} "
                    f"(stale writer or unloaded lineage; use force only for "
                    f"deliberate heals)"
                )
            else:
                persisted_incarnation = int(row[1]) if row[1] is not None else None
                if (
                    expected_incarnation is None
                    or persisted_incarnation is None
                    or int(row[2] or 0)
                    or int(expected_incarnation) != persisted_incarnation
                ):
                    raise StaleSessionWriteError(
                        f"Refusing to overwrite session {sid!r}: expected "
                        f"incarnation {expected_incarnation!r} != persisted "
                        f"{persisted_incarnation!r}; the session was deleted "
                        f"and recreated — reload"
                    )
                new_generation = current_generation + 1
                cas_guard = True
        else:
            authority = conn.execute(
                "SELECT incarnation, retired FROM session_incarnations "
                "WHERE session_id = %s",
                (sid,),
            ).fetchone()
            if authority is None:
                if expected_generation is not None:
                    raise DeletedSessionWriteError(
                        f"Refusing to write session {sid!r}: writer carries "
                        f"generation {expected_generation!r} but no session was "
                        f"ever persisted under this id (deleted or never existed)"
                    )
                conn.execute(
                    "INSERT INTO session_incarnations "
                    "(session_id, incarnation, retired, retired_generation) "
                    "VALUES (%s, 1, 0, 0)",
                    (sid,),
                )
                new_generation = 1
            elif not int(authority[1]):
                raise StaleSessionWriteError(
                    f"Refusing to write session {sid!r}: incarnation authority "
                    f"says the session is live but the row is absent "
                    f"(orphaned authority; failing closed)"
                )
            elif expected_generation is not None:
                raise DeletedSessionWriteError(
                    f"Refusing to write session {sid!r}: writer carries "
                    f"generation {expected_generation!r} from before the "
                    f"session was deleted (stale writer after delete)"
                )
            elif not fresh_incarnation:
                raise RetiredSessionWriteError(
                    f"Refusing to recreate session {sid!r}: the id is retired "
                    f"(deleted); only an explicit recreate with "
                    f"fresh_incarnation=True may lease a new incarnation"
                )
            else:
                conn.execute(
                    "UPDATE session_incarnations "
                    "SET incarnation = incarnation + 1, retired = 0 "
                    "WHERE session_id = %s",
                    (sid,),
                )
                new_generation = 1

        cols.append("generation")
        vals.append(new_generation)

        placeholders = ", ".join("%s" for _ in cols)
        upsert_sql = (
            f"INSERT INTO sessions ({', '.join(cols)}) VALUES ({placeholders}) "
            "ON CONFLICT(session_id) DO UPDATE SET "
            + ", ".join(f"{c}=excluded.{c}" for c in cols)
        )
        if cas_guard:
            # Enforce the fence in the statement itself: Postgres READ
            # COMMITTED gives each statement a fresh snapshot, so a
            # SELECT-then-UPDATE inside one transaction could otherwise see
            # a newer row than the probe above.
            cur = conn.execute(
                upsert_sql
                + " WHERE sessions.generation = %s "
                  "AND EXISTS (SELECT 1 FROM session_incarnations i "
                  "WHERE i.session_id = sessions.session_id "
                  "AND i.incarnation = %s AND i.retired = 0)",
                vals + [int(expected_generation), int(expected_incarnation)],
            )
            if cur.rowcount != 1:
                probe = conn.execute(
                    "SELECT s.generation AS generation, "
                    "i.incarnation AS incarnation "
                    "FROM sessions s "
                    "LEFT JOIN session_incarnations i "
                    "ON i.session_id = s.session_id "
                    "WHERE s.session_id = %s",
                    (sid,),
                ).fetchone()
                raise StaleSessionWriteError(
                    f"Refusing to overwrite session {sid!r}: "
                    f"generation/incarnation moved under the write "
                    f"(persisted: {tuple(probe) if probe is not None else None!r}); "
                    f"reload and retry"
                )
        else:
            conn.execute(upsert_sql, vals)

    def _write_json_table(self, conn, table: str, column: str, sid: str, rows: list[Any]) -> None:
        conn.execute(f"DELETE FROM {table} WHERE session_id = %s", (sid,))
        for idx, row in enumerate(rows):
            if not isinstance(row, dict):
                continue
            conn.execute(
                f"INSERT INTO {table} (session_id, idx, {column}) VALUES (%s, %s, %s)",
                (sid, idx, _json_dump(row)),
            )

    def _write_anchor_scenes(self, conn, sid: str, scenes: Any) -> None:
        conn.execute("DELETE FROM anchor_scenes WHERE session_id = %s", (sid,))
        if not isinstance(scenes, dict):
            return
        for hsh, scene in scenes.items():
            conn.execute(
                "INSERT INTO anchor_scenes (scene_hash, session_id, scene_json) VALUES (%s, %s, %s)",
                (hsh, sid, _json_dump(scene)),
            )

    _METADATA_UNSAFE_FIELDS = frozenset(
        {"session_id", "messages", "tool_calls", "message_count", "generation"}
    )

    def _apply_metadata_fields(self, conn, sid: str, fields: dict[str, Any]) -> tuple[list[str], list[Any]]:
        """Build (set_parts, values) for a targeted metadata UPDATE.

        Same field-application policy as the SQLite store: column/JSON
        classification, extra_json merge, null_fields_json maintenance.
        updated_at rides in fields and is a scalar column, so the loop
        already covers it; Postgres rejects duplicate assignments. Does NOT
        append the sid placeholder or the generation bump.
        """
        set_parts: list[str] = []
        values: list[Any] = []
        extras: dict[str, Any] = {}
        for k, v in fields.items():
            if k in _SESSION_JSON_FIELDS:
                set_parts.append(f"{k} = %s")
                values.append(None if v is None else _json_dump(v))
            elif k in _SESSION_SCALAR_FIELDS:
                set_parts.append(f"{k} = %s")
                values.append(v)
            else:
                extras[k] = v
        # Maintain null key-presence across targeted updates.
        row = conn.execute(
            "SELECT null_fields_json FROM sessions WHERE session_id = %s", (sid,)
        ).fetchone()
        null_fields: list[str] = []
        if row is not None and row[0]:
            try:
                parsed = json.loads(row[0])
                if isinstance(parsed, list):
                    null_fields = [x for x in parsed if isinstance(x, str)]
            except (json.JSONDecodeError, TypeError):
                pass
        for k, v in fields.items():
            if v is None:
                if k not in null_fields:
                    null_fields.append(k)
            elif k in null_fields:
                null_fields.remove(k)
        set_parts.append("null_fields_json = %s")
        values.append(_json_dump(null_fields) if null_fields else None)
        if extras:
            row = conn.execute(
                "SELECT extra_json FROM sessions WHERE session_id = %s", (sid,)
            ).fetchone()
            current: dict[str, Any] = {}
            if row is not None and row[0]:
                try:
                    parsed = json.loads(row[0])
                    if isinstance(parsed, dict):
                        current = parsed
                except (json.JSONDecodeError, TypeError):
                    pass
            current.update(extras)
            set_parts.append("extra_json = %s")
            values.append(_json_dump(current))
        return set_parts, values

    def update_metadata(
        self,
        sid: str,
        fields: dict[str, Any],
        *,
        expected_generation: int | None = None,
        expected_incarnation: int | None = None,
    ) -> dict[str, Any]:
        if not isinstance(fields, dict):
            raise TypeError("fields must be a dict")
        unsafe = set(fields) & self._METADATA_UNSAFE_FIELDS
        if unsafe:
            raise ValueError(f"Unsafe session metadata fields: {', '.join(sorted(unsafe))}")

        conn = self._conn()
        with conn:
            # The metadata write is a versioned writer: both halves of the
            # (generation, incarnation) token are required and validated in
            # the same transaction that applies the fields. Field validation
            # above stays token-free (TypeError/ValueError before any SQL).
            row = conn.execute(
                "SELECT s.generation AS generation, i.incarnation AS incarnation, "
                "i.retired AS retired "
                "FROM sessions s "
                "LEFT JOIN session_incarnations i ON i.session_id = s.session_id "
                "WHERE s.session_id = %s",
                (sid,),
            ).fetchone()
            if row is None:
                raise DeletedSessionWriteError(
                    f"Refusing metadata write for session {sid!r}: no live row "
                    f"(deleted or never persisted)"
                )
            current_generation = int(row[0] or 0)
            persisted_incarnation = int(row[1]) if row[1] is not None else None
            if expected_generation is None or expected_incarnation is None:
                raise StaleSessionWriteError(
                    f"Refusing metadata write for session {sid!r}: unversioned "
                    f"metadata write refused: load the durable version first"
                )
            if persisted_incarnation is None or int(row[2] or 0):
                raise StaleSessionWriteError(
                    f"Refusing metadata write for session {sid!r}: incarnation "
                    f"authority is missing or retired (failing closed)"
                )
            if int(expected_generation) != current_generation:
                raise StaleSessionWriteError(
                    f"Refusing metadata write for session {sid!r}: expected "
                    f"generation {expected_generation!r} != persisted "
                    f"{current_generation!r} (stale writer; reload)"
                )
            if int(expected_incarnation) != persisted_incarnation:
                raise StaleSessionWriteError(
                    f"Refusing metadata write for session {sid!r}: expected "
                    f"incarnation {expected_incarnation!r} != persisted "
                    f"{persisted_incarnation!r}; the session was deleted and "
                    f"recreated — reload"
                )
            self._bump_revision(conn)
            set_parts, values = self._apply_metadata_fields(conn, sid, fields)
            # Metadata-only writers move the same version fence as full
            # writes (generation is never in fields, so appending is safe).
            # The guard enforces the fence in the statement itself (a fresh
            # statement snapshot must not see a newer row than the probe).
            set_parts.append("generation = generation + 1")
            values.extend([sid, int(expected_generation), int(expected_incarnation)])
            cur = conn.execute(
                f"UPDATE sessions SET {', '.join(set_parts)} "
                "WHERE session_id = %s AND generation = %s "
                "AND EXISTS (SELECT 1 FROM session_incarnations i "
                "WHERE i.session_id = sessions.session_id "
                "AND i.incarnation = %s AND i.retired = 0)",
                values,
            )
            if cur.rowcount != 1:
                probe = conn.execute(
                    "SELECT 1 FROM sessions WHERE session_id = %s", (sid,)
                ).fetchone()
                if probe is None:
                    raise DeletedSessionWriteError(
                        f"Refusing metadata write for session {sid!r}: the row "
                        f"disappeared under the write (deleted)"
                    )
                raise StaleSessionWriteError(
                    f"Refusing metadata write for session {sid!r}: "
                    f"generation/incarnation moved under the write; reload"
                )
        return self.read_metadata_only(sid) or {}

    def read_row_version(self, sid: str) -> dict[str, int] | None:
        """Durable (generation, incarnation) of the live row (contract).

        One indexed JOIN against the incarnation authority; read-only.
        Returns None for an absent or retired row.
        """
        if not _is_safe_session_id(sid):
            return None
        row = self._conn().execute(
            "SELECT s.generation AS generation, i.incarnation AS incarnation, "
            "i.retired AS retired "
            "FROM sessions s JOIN session_incarnations i "
            "ON i.session_id = s.session_id "
            "WHERE s.session_id = %s",
            (sid,),
        ).fetchone()
        if row is None or int(row[2]):
            return None
        return {"generation": int(row[0] or 0), "incarnation": int(row[1])}

    def reconcile_marked_write(
        self,
        sid: str,
        *,
        expected_generation: int,
        expected_incarnation: int,
        fields: dict[str, Any],
    ) -> dict[str, Any] | None:
        """Atomically overlay proven-dirty metadata onto a recovered row whose
        durable version still matches the fallback-load baseline. Fail closed
        (None, nothing written) on any generation/incarnation mismatch."""
        if not _is_safe_session_id(sid):
            return None
        if not isinstance(fields, dict):
            raise TypeError("fields must be a dict")
        unsafe = set(fields) & self._METADATA_UNSAFE_FIELDS
        if unsafe:
            raise ValueError(f"Unsafe session metadata fields: {', '.join(sorted(unsafe))}")

        conn = self._conn()
        with conn:
            row = conn.execute(
                "SELECT generation FROM sessions WHERE session_id = %s", (sid,)
            ).fetchone()
            authority = conn.execute(
                "SELECT incarnation, retired FROM session_incarnations "
                "WHERE session_id = %s",
                (sid,),
            ).fetchone()
            if (
                row is None
                or authority is None
                or int(authority[1])
                or int(authority[0]) != int(expected_incarnation)
                or int(row[0] or 0) != int(expected_generation)
            ):
                return None  # fail closed; nothing written
            self._bump_revision(conn)
            set_parts, values = self._apply_metadata_fields(conn, sid, fields)
            set_parts.append("generation = generation + 1")
            values.extend([sid, int(expected_generation), int(expected_incarnation)])
            cur = conn.execute(
                f"UPDATE sessions SET {', '.join(set_parts)} "
                "WHERE session_id = %s AND generation = %s "
                "AND EXISTS (SELECT 1 FROM session_incarnations i "
                "WHERE i.session_id = sessions.session_id "
                "AND i.incarnation = %s AND i.retired = 0)",
                values,
            )
            if cur.rowcount != 1:
                return None  # CAS belt-and-braces inside the txn
        return self.read_session(sid)

    def delete_session(self, sid: str, *, _txn=None) -> bool:
        """``_txn`` is the internal caller-owned transaction used by
        ``lifecycle_delete`` so the delete and its residual-phase rows
        commit atomically; public callers never pass it."""
        if not _is_safe_session_id(sid):
            return False
        if _txn is not None:
            return self._delete_session_in_txn(_txn, sid)
        with self._conn() as conn:
            return self._delete_session_in_txn(conn, sid)

    def _delete_session_in_txn(self, conn, sid: str) -> bool:
        """The authoritative delete body; the CALLER owns the transaction.

        Split out so ``lifecycle_delete(pending_phases=...)`` can delete the
        rows and record the residual-cleanup phases in ONE transaction — no
        crash window between "store deleted" and "residuals durably
        observable".
        """
        self._bump_revision(conn)
        row = conn.execute(
            "SELECT generation FROM sessions WHERE session_id = %s", (sid,)
        ).fetchone()
        old_generation = int(row[0] or 0) if row is not None else 0
        cur = conn.execute("DELETE FROM sessions WHERE session_id = %s", (sid,))
        conn.execute("DELETE FROM messages WHERE session_id = %s", (sid,))
        conn.execute("DELETE FROM tool_calls WHERE session_id = %s", (sid,))
        conn.execute("DELETE FROM context_messages WHERE session_id = %s", (sid,))
        conn.execute("DELETE FROM anchor_scenes WHERE session_id = %s", (sid,))
        if cur.rowcount > 0:
            # Retire the SID; the incarnation counter does not move on
            # delete — only a leased recreate advances it.
            conn.execute(
                "INSERT INTO session_incarnations "
                "(session_id, incarnation, retired, retired_generation) "
                "VALUES (%s, 1, 1, %s) "
                "ON CONFLICT (session_id) DO UPDATE SET "
                "retired = 1, retired_generation = EXCLUDED.retired_generation",
                (sid, old_generation),
            )
        return cur.rowcount > 0

    def lifecycle_delete(
        self,
        sid: str,
        *,
        owner: str,
        pending_phases: Sequence[str] | None = None,
    ) -> dict[str, Any]:
        """Delete with durable retry ownership (SessionStore contract).

        Success clears any cleanup lease for ``sid``; failure records a
        lease keyed by ``sid`` so the retry owner survives a crash. Never
        touches the JSON sidecar.

        ``pending_phases``: residual-cleanup phase names recorded IN THE
        SAME transaction as the authoritative delete (upserted into
        ``cleanup_phases``; ON CONFLICT preserves ``attempts`` and refreshes
        owner/updated_at). Default None means delete + lease handling only
        (unchanged behavior). Leases and phases never coexist for a sid.
        """
        try:
            if pending_phases:
                with self._conn() as conn:
                    # Route through the public delete_session seam (the
                    # delete failure-injection point) with the caller-owned
                    # transaction, so rows + phase rows commit atomically.
                    existed = self.delete_session(sid, _txn=conn)
                    conn.execute("DELETE FROM cleanup_leases WHERE session_id = %s", (sid,))
                    now = time.time()
                    for phase in pending_phases:
                        conn.execute(
                            "INSERT INTO cleanup_phases "
                            "(session_id, phase, owner, error, updated_at, attempts) "
                            "VALUES (%s, %s, %s, NULL, %s, 0) "
                            "ON CONFLICT (session_id, phase) DO UPDATE SET "
                            "owner = EXCLUDED.owner, updated_at = EXCLUDED.updated_at",
                            (sid, phase, owner, now),
                        )
            else:
                existed = self.delete_session(sid)
                with self._conn() as conn:
                    conn.execute("DELETE FROM cleanup_leases WHERE session_id = %s", (sid,))
        except Exception as exc:
            # psycopg3 closes the connection at the end of each `with conn:`
            # block, so every step below re-fetches a live connection.
            self._conn().rollback()
            error = f"{type(exc).__name__}: {exc}"
            with self._conn() as conn:
                conn.execute(
                    "INSERT INTO cleanup_leases "
                    "(session_id, owner, error, updated_at, attempts) "
                    "VALUES (%s, %s, %s, %s, 1) "
                    "ON CONFLICT (session_id) DO UPDATE SET "
                    "owner = EXCLUDED.owner, error = EXCLUDED.error, "
                    "updated_at = EXCLUDED.updated_at, "
                    "attempts = cleanup_leases.attempts + 1",
                    (sid, owner, error, time.time()),
                )
            try:
                existed = self.session_exists(sid)
            except Exception:
                existed = False
            return {"ok": False, "error": error, "existed": existed}
        return {"ok": True, "existed": bool(existed)}

    def finish_cleanup_phase(
        self, sid: str, phase: str, *, ok: bool, error: str | None = None
    ) -> None:
        """Record one residual-cleanup attempt: ok clears the row; failure
        updates error/updated_at and bumps attempts."""
        with self._conn() as conn:
            if ok:
                conn.execute(
                    "DELETE FROM cleanup_phases WHERE session_id = %s AND phase = %s",
                    (sid, phase),
                )
            else:
                conn.execute(
                    "UPDATE cleanup_phases SET error = %s, updated_at = %s, "
                    "attempts = cleanup_phases.attempts + 1 "
                    "WHERE session_id = %s AND phase = %s",
                    (error, time.time(), sid, phase),
                )

    def list_cleanup_phases(self, sid: str | None = None) -> list[dict[str, Any]]:
        """Remaining residual-cleanup phase rows (for ``sid``, or every row
        for a janitor sweep), ordered by session_id, phase."""
        conn = self._conn()
        if sid is None:
            cur = conn.execute(
                "SELECT session_id, phase, owner, error, updated_at, attempts "
                "FROM cleanup_phases ORDER BY session_id, phase"
            )
        else:
            cur = conn.execute(
                "SELECT session_id, phase, owner, error, updated_at, attempts "
                "FROM cleanup_phases WHERE session_id = %s "
                "ORDER BY session_id, phase",
                (sid,),
            )
        cols = [d.name if hasattr(d, "name") else d[0] for d in cur.description]
        return [dict(zip(cols, row)) for row in cur.fetchall()]

    def list_cleanup_leases(self, owner: str | None = None) -> list[dict[str, Any]]:
        """Durable retry leases recorded by failed ``lifecycle_delete`` calls."""
        conn = self._conn()
        if owner is None:
            cur = conn.execute(
                "SELECT session_id, owner, error, updated_at, attempts "
                "FROM cleanup_leases ORDER BY updated_at"
            )
        else:
            cur = conn.execute(
                "SELECT session_id, owner, error, updated_at, attempts "
                "FROM cleanup_leases WHERE owner = %s ORDER BY updated_at",
                (owner,),
            )
        cols = [d.name if hasattr(d, "name") else d[0] for d in cur.description]
        return [dict(zip(cols, row)) for row in cur.fetchall()]

    def archive(
        self,
        sid: str,
        archived: bool = True,
        *,
        expected_generation: int | None = None,
        expected_incarnation: int | None = None,
    ) -> dict[str, Any]:
        # Pass-through: strictness is inherited from update_metadata, so any
        # caller must be a versioned writer carrying both token halves.
        return self.update_metadata(
            sid,
            {"archived": 1 if archived else 0},
            expected_generation=expected_generation,
            expected_incarnation=expected_incarnation,
        )

    # -- row mapping (mirrors the SQLite store) ----------------------------

    def _row_to_metadata(self, d: dict[str, Any], *, include_computed: bool = True) -> dict[str, Any]:
        row: dict[str, Any] = {"session_id": d["session_id"]}
        for field in _SESSION_SCALAR_FIELDS:
            if field == "anchor_scene_index_hash":
                continue
            v = d.get(field)
            if v is None and field not in _ALWAYS_PRESENT_FIELDS:
                continue
            if field in _SESSION_JSON_FIELDS and isinstance(v, str):
                v = json.loads(v)
            elif field in _SESSION_BOOL_FIELDS and v is not None:
                v = bool(v)
            row[field] = v
        if include_computed:
            row["last_message_at"] = d.get("updated_at") or d.get("created_at")
        extra_json = d.get("extra_json")
        if extra_json:
            try:
                extra = json.loads(extra_json)
            except (json.JSONDecodeError, TypeError):
                extra = None
            if isinstance(extra, dict):
                for k, v in extra.items():
                    row.setdefault(k, v)
        null_fields_json = d.get("null_fields_json")
        if null_fields_json:
            try:
                null_fields = json.loads(null_fields_json)
            except (json.JSONDecodeError, TypeError):
                null_fields = None
            if isinstance(null_fields, list):
                for k in null_fields:
                    if isinstance(k, str):
                        row[k] = None
        if d.get("generation") is not None:
            row["generation"] = d["generation"]
        if d.get("incarnation") is not None:
            row["incarnation"] = d["incarnation"]
        return row

    def _row_to_session(self, d: dict[str, Any]) -> dict[str, Any]:
        session = self._row_to_metadata(d, include_computed=False)
        scenes_json = d.get("anchor_activity_scenes_json")
        if scenes_json is not None:
            session["anchor_activity_scenes"] = json.loads(scenes_json)
        return session
